version: "2"
services:
    flask_api_endpoint_web:
        container_name: flask_api_endpoint_web
        image: articleproduction/flask_api_1.0.0
        build:
            context: ./
            target: web
    flask_api_endpoint_worker:
        container_name: flask_api_endpoint_worker
        image: articleproduction/flask_api_1.0.0
        build:
            context: ./
            target: worker
