# This is a basic workflow to help you get started with Actions

name: Build docker container for article production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs the docker build
      - name: docker login
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
        run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD

      # Runs the docker build
      - name: docker build
        run: |
          docker build ./Code/Backend -t article_production_flask/api/1.0.0
          
      # Push the new image
      - name: docker push
        run: |
          docker push article_production_flask/api/1.0.0

