# This is a basic workflow to help you get started with Actions

name: Build docker container for article production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs the docker build
      - name: docker login
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
        run: |
          docker login -u $HEROKU_EMAIL -p $HEROKU_API_KEY registry.heroku.com
      # Runs the docker build
      - name: docker web build
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: |
          docker build ./Code/Backend/Docker/web -t registry.heroku.com/$HEROKU_APP_NAME/web
        
      # Push the new image
      - name: docker web push
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}  
        run: |
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          
        # Release the new Heroku conatiner
      - name: heroku web container release
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
        run: |
          heroku container:login
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
          
      # Steps for Worker
    
        # Runs the docker build
      - name: docker worker build
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: |
          docker build ./Code/Backend/Docker/worker -t registry.heroku.com/$HEROKU_APP_NAME/worker
        
      # Push the new image
      - name: docker worker push
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}  
        run: |
          docker push registry.heroku.com/$HEROKU_APP_NAME/worker
          
        # Release the new Heroku conatiner
      - name: heroku worker container release
        env:
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
        run: |
          heroku container:login
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} worker
      
      
          

